- name: Push to hub
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    git config user.email "action@github.com"
    git config user.name "GitHub Action"
    git pull https://vamsi-guttula-ds:$HF_TOKEN@huggingface.co/spaces/vamsi-guttula-ds/test2_vamsi main --rebase
    git push https://vamsi-guttula-ds:$HF_TOKEN@huggingface.co/spaces/vamsi-guttula-ds/test2_vamsi main
